# Generated by Django 4.0.1 on 2022-01-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='dishname',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='phone',
            new_name='price',
        ),
    ]
