# Generated by Django 4.0.1 on 2022-02-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_name_menu_dishname_rename_phone_menu_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='chappan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=120)),
                ('shop_number', models.SmallIntegerField(max_length=12)),
                ('dishname', models.CharField(max_length=120)),
                ('cuisines', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='menu',
        ),
    ]
