# Generated by Django 4.0.1 on 2022-02-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_chappan_delete_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='chinese_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('food_price', models.IntegerField()),
            ],
        ),
    ]
