# Generated by Django 4.0.1 on 2022-02-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_chinese_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=20)),
                ('employee_id', models.IntegerField(null=True)),
                ('employee_salary', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=20)),
                ('owner_age', models.IntegerField()),
                ('owner_contact', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='chappan',
        ),
        migrations.DeleteModel(
            name='chinese_food',
        ),
    ]
