# Generated by Django 4.0.1 on 2022-02-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_employee_owner_delete_chappan_delete_chinese_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
