# Generated by Django 4.0.1 on 2022-02-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_employee_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_age',
            field=models.SmallIntegerField(),
        ),
    ]
