# Generated by Django 4.0.1 on 2022-02-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_owner_owner_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='total_employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_employees', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_address',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
